CREATE TABLE STOCK (
	PRODUCTID           BIGINT NOT NULL PRIMARY KEY,
	PRODUCTNAME         VARCHAR(50) NOT NULL,
	STOCK_QUANTITY      INT,
	STOCK_LOCATION      VARCHAR(50)
)

CREATE TABLE SALE (
	PRODUCTID           BIGINT NOT NULL PRIMARY KEY,
	SALE_COUNT          INT,
	SALE_DATE           DATETIME
)
